/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// Widget groups
#define GROUP_DEFAULT 0

// GListeners
extern GListener gl;

// GHandles
extern GHandle ghContainerControl;
extern GHandle ghButtonInc;
extern GHandle ghButtonDec;
extern GHandle ghButtonInc10;
extern GHandle ghButtonDec10;
extern GHandle ghProgressbar1;
extern GHandle ghLabelProgress;
extern GHandle ghList1;
extern GHandle ghButtonClearMsg;
extern GHandle ghButtonScreenSettings;
extern GHandle ghContainerSettings;
extern GHandle ghContainer3;
extern GHandle ghRadiobutton50;
extern GHandle ghRadiobutton25;
extern GHandle ghRadiobutton5;
extern GHandle ghRadiobutton10;
extern GHandle ghButtonScreenControl;
extern GHandle ghLabel1;
extern GHandle ghImagebox1;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

