/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerPage0;
GHandle default_pg;
GHandle touch_button_df_pg;
GHandle ghContainerPage1;
GHandle ghKeyboard1;
GHandle ghTextedit1;
GHandle ghLabel1;
GHandle ghLabel2;
GHandle ghContainerCloud_user_startup;

// Fonts
font_t dejavu_sans_16;
font_t dejavu_sans_12;
font_t dejavu_sans_24;

// Images
gdispImage Cloud_USER;

static void containerDraw_Unnamed(GWidgetObject* gw, void* param)
{
	(void)param;

	// Clear container area
	gdispGFillArea(gw->g.display, gw->g.x, gw->g.y, gw->g.width, gw->g.height, gw->pstyle->background);

	// Draw the elements
}

static void containerDraw_Cloud_user_bg(GWidgetObject* gw, void* param)
{
	(void)param;

	// Clear container area
	gdispGFillArea(gw->g.display, gw->g.x, gw->g.y, gw->g.width, gw->g.height, gw->pstyle->background);

	// Draw the elements
	gdispImageDraw(&Cloud_USER, 0, 0, 480, 272, 0, 0);
}

static void createPagePage0(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerPage0
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 480;
	wi.g.height = 272;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = containerDraw_Unnamed;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPage0 = gwinContainerCreate(0, &wi, 0);

	// create button widget: default_pg
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 480;
	wi.g.height = 272;
	wi.g.parent = ghContainerPage0;
	default_pg = gwinImageCreate(0, &wi.g);
	gwinImageOpenFile(default_pg, "rsc/ACCESS_CONTROL.BMP");

	// create button widget: touch_button_df_pg
	wi.g.show = TRUE;
	wi.g.x = 200;
	wi.g.y = 20;
	wi.g.width = 120;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "TOUCH";
	wi.customDraw = gwinButtonDraw_Rounded;
	wi.customParam = 0;
	wi.customStyle = &white;
	touch_button_df_pg = gwinButtonCreate(0, &wi);
	gwinSetFont(touch_button_df_pg, dejavu_sans_12);
	gwinRedraw(touch_button_df_pg);
}

static void createPagePage1(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerPage1
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 480;
	wi.g.height = 272;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPage1 = gwinContainerCreate(0, &wi, 0);

	// Create keyboard widget: ghKeyboard1
	wi.g.show = TRUE;
	wi.g.x = -3;
	wi.g.y = 124;
	wi.g.width = 483;
	wi.g.height = 148;
	wi.g.parent = ghContainerPage1;
	wi.text = "Keyboard1";
	wi.customDraw = gwinKeyboardDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghKeyboard1 = gwinKeyboardCreate(0, &wi);

	// Create textedit widget: ghTextedit1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 39;
	wi.g.width = 178;
	wi.g.height = 61;
	wi.g.parent = ghContainerPage1;
	wi.text = "Enter your Pin ";
	wi.customDraw = gwinTexteditDefaultDraw;
	wi.customParam = 0;
	wi.customStyle = &white;
	ghTextedit1 = gwinTexteditCreate(0, &wi, 0);
	gwinSetFont(ghTextedit1, dejavu_sans_24);
	gwinRedraw(ghTextedit1);

	// Create label widget: ghLabel1
	wi.g.show = TRUE;
	wi.g.x = 400;
	wi.g.y = 0;
	wi.g.width = 78;
	wi.g.height = 18;
	wi.g.parent = ghContainerPage1;
	wi.text = "hr:mm:ss";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel1 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel1, FALSE);

	// Create label widget: ghLabel2
	wi.g.show = TRUE;
	wi.g.x = 340;
	wi.g.y = 0;
	wi.g.width = 38;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage1;
	wi.text = "date";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghLabel2 = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghLabel2, FALSE);
}

static void createPageCloud_user_startup(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerCloud_user_startup
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 480;
	wi.g.height = 272;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = containerDraw_Cloud_user_bg;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerCloud_user_startup = gwinContainerCreate(0, &wi, 0);
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerPage0);
	gwinHide(ghContainerPage1);
	gwinHide(ghContainerCloud_user_startup);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerPage0);
		break;

	case 1:
		gwinShow(ghContainerPage1);
		break;

	case 2:
		gwinShow(ghContainerCloud_user_startup);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");
	dejavu_sans_12 = gdispOpenFont("DejaVuSans12");
	dejavu_sans_24 = gdispOpenFont("DejaVuSans24");

	// Prepare images
	gdispImageOpenFile(&Cloud_USER, "rsc/Cloud_USER.gif");

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);

	// Create all the display pages
	createPagePage0();
	createPagePage1();
	createPageCloud_user_startup();

	// Select the default display page
	guiShowPage(2);

}

void guiEventLoop(void)
{
	GEvent* pe;

	while (1) {
		// Get an event
		pe = geventEventWait(&glistener, 0);
		switch (pe->type) {
		}

	}
}

