/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle default_pg;
extern GHandle touch_button_df_pg;
extern GHandle ghContainerPage1;
extern GHandle ghKeyboard1;
extern GHandle ghTextedit1;
extern GHandle ghLabel1;
extern GHandle ghLabel2;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

